# Generated by Django 3.0.2 on 2020-01-13 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('expense_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
